# yaml-language-server: $schema=config.schema.yaml
googleProject: dicectf-quals-2024
googleZone: us-east1-b
challengeHost: mc.ax
flagRegex: ^dice\{[!-z|~]+\}$
images:
  registry: us-east1-docker.pkg.dev
  challengesBase: dicectf-quals-2024/deploy
  cacheBase: dicectf-quals-2024/cache
uploads:
  bucket: static.dicega.ng
  prefix: uploads
scoreboard:
  rctf:
    url: https://ctf.dicega.ng
    tokenNames:
      read: rctf-read
      write: rctf-write
    defaultPoints:
      min: 100
      max: 500
deploy:
  kubernetes:
    clusterName: ctf
    defaultResources:
      requests:
        cpu: 25m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 150Mi
monitoring:
  enable: false
